/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_PEG_H
#define PCC_INCLUDED_PEG_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct peg_context_tag peg_context_t;

peg_context_t *peg_create(void *auxil);
int peg_parse(peg_context_t *ctx, int *ret);
void peg_destroy(peg_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_PEG_H */
