/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_TEST_H
#define PCC_INCLUDED_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct test_context_tag test_context_t;

test_context_t *test_create(void *auxil);
int test_parse(test_context_t *ctx, int *ret);
void test_destroy(test_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_TEST_H */
