/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_EXAMPLE_H
#define PCC_INCLUDED_EXAMPLE_H

#include <stdio.h>
#include "ast.h"
#include <string.h>
#ifdef __cplusplus
extern "C" {
#endif

typedef struct example_context_tag example_context_t;

example_context_t *example_create(void *auxil);
int example_parse(example_context_t *ctx, ast_node_t**ret);
void example_destroy(example_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_EXAMPLE_H */
