SRCS = hello_world.sai fac.sai tfac.sai module_calls.sai ackermann.sai message_passing.sai
OBJS = $(SRCS:%=../examples/%)

all: ../SAI.md

../SAI.md: SAI.md.in $(OBJS)
	cp SAI.md.in ../SAI.md
	for obj in $(OBJS); do \
	    sed -i '/__'`basename $$obj`'__/r '$$obj ../SAI.md; \
	    sed -i '/__'`basename $$obj`'__/d' ../SAI.md; \
        done

clean:
