build:
#	dub build --build=unittest --debug=interpreter --debug=scheduler --debug=user
#	dub build --build=unittest --debug=user --debug=scheduler
#	dub build --build=release --debug=user
#	dub build --build=debug --debug=user
	dub build --build=release --debug=user
#	dub build --build=profile

clean:
	dub clean
	rm -f bin/posm
