build:
	dub build --build=unittest --debug=interpreter --debug=scheduler --debug=user
#	dub build --build=unittest --debug=user --debug=scheduler
#	dub build --build=release

clean:
	dub clean
	rm -f bin/posm
