all:
	(cd lint; $(MAKE) all)
	(cd prototype; $(MAKE) all)
	(cd sa; $(MAKE) all)
	(cd sac; $(MAKE) all)
	(cd utils; $(MAKE) all)

clean:
	(cd lint; $(MAKE) clean)
	(cd prototype; $(MAKE) clean)
	(cd sa; $(MAKE) clean)
	(cd sac; $(MAKE) clean)
	(cd utils; $(MAKE) clean)
